"""se adiciona las columnas description, detail_images y rating a la tabla Product

Revision ID: 7977fe899166
Revises: 1fdc432d81fa
Create Date: 2025-06-25 22:10:13.893062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7977fe899166'
down_revision = '1fdc432d81fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('detail_images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('detail_images')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
