roles = [
    "Admin",
    "General"
]
users = [
    
    
    {"email": "jose@gmail.com", 
     "name": "Jose Hernandez", 
     "password": "123456789", 
     "role_id": 2},

    {"email": "maria@gmail.com", 
     "name": "Maria Perez", 
     "password": "123456789", 
     "role_id": 2},

    {"email": "luis@gmail.com", 
     "name": "Luis Miguel", 
     "password": "123456789", 
     "role_id": 2},

    {"email": "sofia@gmail.com", 
     "name": "Sofia Reyes", 
     "password": "123456789", 
     "role_id": 2},

    {"email": "andres@gmail.com", 
     "name": "Andres Romero", 
     "password": "123456789", 
     "role_id": 2},

    {"email": "ana@gmail.com", 
     "name": "Ana Castillo", 
     "password": "123456789", 
     "role_id": 2},

    {"email": "raul@gmail.com", 
     "name": "Raul Paredes", 
     "password": "123456789", 
     "role_id": 2},

    {"email": "carla@gmail.com", 
     "name": "Carla Navarro", 
     "password": "123456789", 
     "role_id": 2},
     
    {"email": "daniel@gmail.com", 
     "name": "Daniel Suárez", 
     "password": "123456789", 
     "role_id": 1},
     
    {"email": "elena@gmail.com", 
     "name": "Elena Figueroa", 
     "password": "123456789", 
     "role_id": 1}
]

    
    
    
    
categories = [
    {"name": "Ciencia ficción"},
    {"name": "Fantasía"},
    {"name": "No ficción"},
    {"name": "Novela histórica"},
    {"name": "Biografía"},
    {"name": "Ensayo"},
    {"name": "Literatura clásica"},
    {"name": "Psicología"},
    {"name": "Misterio"},
    {"name": "Autoayuda"}
]
authors = [
    {"name": "Isaac Asimov"},
    {"name": "J.R.R. Tolkien"},
    {"name": "George Orwell"},
    {"name": "Stephen King"},
    {"name": "Jane Austen"},
    {"name": "Yuval Noah Harari"},
    {"name": "Gabriel García Márquez"},
    {"name": "Dan Brown"},
    {"name": "Victor Hugo"},
    {"name": "Sun Tzu"}
]
products = [
 {
        "name": "Fundación",
        "price": 15.99,
        "image_url": "https://covers.openlibrary.org/b/id/9288212-L.jpg",
        "is_featured": True,
        "description": "Primera novela de la saga de la Fundación de Isaac Asimov.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 30,
        "category_id": 1,
        "author_ids": [1],
    },
    {
        "name": "El Señor de los Anillos: La Comunidad del Anillo",
        "price": 19.99,
        "image_url": "https://covers.openlibrary.org/b/id/8231996-L.jpg",
        "is_featured": True,
        "description": "Primer volumen de la saga de Tolkien.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 25,
        "category_id": 2,
        "author_ids": [2],
    },
    {
        "name": "1984",
        "price": 12.99,
        "image_url": "https://covers.openlibrary.org/b/id/153541-L.jpg",
        "is_featured": True,
        "description": "Distopía clásica escrita por George Orwell.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 40,
        "category_id": 1,
        "author_ids": [3],
    },
    {
        "name": "It",
        "price": 18.75,
        "image_url": "https://covers.openlibrary.org/b/id/7884861-L.jpg",
        "is_featured": False,
        "description": "Terrorífica novela de Stephen King.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 20,
        "category_id": 9,
        "author_ids": [4],
    },
    {
        "name": "Orgullo y prejuicio",
        "price": 10.50,
        "image_url": "https://covers.openlibrary.org/b/id/8221255-L.jpg",
        "is_featured": True,
        "description": "Obra maestra de Jane Austen.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 15,
        "category_id": 7,
        "author_ids": [5],
    },
    {
        "name": "Sapiens: De animales a dioses",
        "price": 17.99,
        "image_url": "https://covers.openlibrary.org/b/id/8312161-L.jpg",
        "is_featured": True,
        "description": "Historia de la humanidad por Yuval Noah Harari.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 50,
        "category_id": 3,
        "author_ids": [6],
    },
    {
        "name": "Cien años de soledad",
        "price": 14.99,
        "image_url": "https://covers.openlibrary.org/b/id/8228691-L.jpg",
        "is_featured": True,
        "description": "Obra cumbre del realismo mágico de García Márquez.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 35,
        "category_id": 7,
        "author_ids": [7],
    },
    {
        "name": "Ángeles y demonios",
        "price": 13.99,
        "image_url": "https://covers.openlibrary.org/b/id/240218-L.jpg",
        "is_featured": False,
        "description": "Thriller de misterio por Dan Brown.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 22,
        "category_id": 9,
        "author_ids": [8],
    },
    {
        "name": "Los miserables",
        "price": 16.99,
        "image_url": "https://covers.openlibrary.org/b/id/11155842-L.jpg",
        "is_featured": True,
        "description": "Clásico histórico de Victor Hugo.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 28,
        "category_id": 4,
        "author_ids": [9],
    },
    {
        "name": "El arte de la guerra",
        "price": 9.99,
        "image_url": "https://covers.openlibrary.org/b/id/8226096-L.jpg",
        "is_featured": False,
        "description": "Tratado militar y filosófico de Sun Tzu.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 50,
        "category_id": 6,
        "author_ids": [10],
    },
    {
        "name": "La guerra de los mundos",
        "price": 12.49,
        "image_url": "https://covers.openlibrary.org/b/id/8218694-L.jpg",
        "is_featured": False,
        "description": "Clásico de ciencia ficción de H.G. Wells.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 30,
        "category_id": 1,
        "author_ids": [1],
    },
    {
        "name": "El Hobbit",
        "price": 13.49,
        "image_url": "https://covers.openlibrary.org/b/id/8101350-L.jpg",
        "is_featured": True,
        "description": "Precuela de El Señor de los Anillos.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 30,
        "category_id": 2,
        "author_ids": [2],
    },
    {
        "name": "Animal Farm",
        "price": 9.99,
        "image_url": "https://covers.openlibrary.org/b/id/8775117-L.jpg",
        "is_featured": False,
        "description": "Alegoría política de Orwell.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 20,
        "category_id": 1,
        "author_ids": [3],
    },
    {
        "name": "Carrie",
        "price": 10.99,
        "image_url": "https://covers.openlibrary.org/b/id/8234669-L.jpg",
        "is_featured": False,
        "description": "Primera novela publicada por Stephen King.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 18,
        "category_id": 9,
        "author_ids": [4],
    },
    {
        "name": "Emma",
        "price": 11.99,
        "image_url": "https://covers.openlibrary.org/b/id/7222246-L.jpg",
        "is_featured": False,
        "description": "Novela de costumbres de Jane Austen.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 16,
        "category_id": 7,
        "author_ids": [5],
    },
    {
        "name": "Homo Deus",
        "price": 18.50,
        "image_url": "https://covers.openlibrary.org/b/id/11123387-L.jpg",
        "is_featured": False,
        "description": "Futuro de la humanidad según Harari.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 40,
        "category_id": 3,
        "author_ids": [6],
    },
    {
        "name": "El coronel no tiene quien le escriba",
        "price": 10.49,
        "image_url": "https://covers.openlibrary.org/b/id/8130075-L.jpg",
        "is_featured": False,
        "description": "Novela corta de Gabriel García Márquez.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 15,
        "category_id": 7,
        "author_ids": [7],
    },
    {
        "name": "Inferno",
        "price": 14.29,
        "image_url": "https://covers.openlibrary.org/b/id/8184861-L.jpg",
        "is_featured": True,
        "description": "Otra entrega de la saga de Robert Langdon.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 22,
        "category_id": 9,
        "author_ids": [8],
    },
    {
        "name": "Notre-Dame de París",
        "price": 15.75,
        "image_url": "https://covers.openlibrary.org/b/id/11142332-L.jpg",
        "is_featured": False,
        "description": "También conocida como El jorobado de Notre-Dame.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 25,
        "category_id": 4,
        "author_ids": [9],
    },
    {
        "name": "12 reglas para vivir",
        "price": 16.95,
        "image_url": "https://covers.openlibrary.org/b/id/9237916-L.jpg",
        "is_featured": True,
        "description": "Guía práctica de Jordan B. Peterson.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 35,
        "category_id": 10,
        "author_ids": [10],
    }
    
]