roles = [
    "Admin",
    "General"
]
users = [


    {"email": "jose@gmail.com",
     "name": "Jose Hernandez",
     "password": "123456789",
     "role_id": 2},

    {"email": "maria@gmail.com",
     "name": "Maria Perez",
     "password": "123456789",
     "role_id": 2},

    {"email": "luis@gmail.com",
     "name": "Luis Miguel",
     "password": "123456789",
     "role_id": 2},

    {"email": "sofia@gmail.com",
     "name": "Sofia Reyes",
     "password": "123456789",
     "role_id": 2},

    {"email": "andres@gmail.com",
     "name": "Andres Romero",
     "password": "123456789",
     "role_id": 2},

    {"email": "ana@gmail.com",
     "name": "Ana Castillo",
     "password": "123456789",
     "role_id": 2},

    {"email": "raul@gmail.com",
     "name": "Raul Paredes",
     "password": "123456789",
     "role_id": 2},

    {"email": "carla@gmail.com",
     "name": "Carla Navarro",
     "password": "123456789",
     "role_id": 2},

    {"email": "daniel@gmail.com",
     "name": "Daniel Suárez",
     "password": "123456789",
     "role_id": 1},

    {"email": "elena@gmail.com",
     "name": "Elena Figueroa",
     "password": "123456789",
     "role_id": 1}
]


categories = [
    {"name": "Ciencia ficción"},
    {"name": "Fantasía"},
    {"name": "No ficción"},
    {"name": "Novela histórica"},
    {"name": "Biografía"},
    {"name": "Ensayo"},
    {"name": "Literatura clásica"},
    {"name": "Psicología"},
    {"name": "Misterio"},
    {"name": "Autoayuda"}
]
authors = [
    {"name": "Isaac Asimov"},
    {"name": "J.R.R. Tolkien"},
    {"name": "George Orwell"},
    {"name": "Stephen King"},
    {"name": "Jane Austen"},
    {"name": "Yuval Noah Harari"},
    {"name": "Gabriel García Márquez"},
    {"name": "Dan Brown"},
    {"name": "Victor Hugo"},
    {"name": "Sun Tzu"},
    {"name": "Jordan B Peterson"},
]
products = [
    {
        "name": "Fundación",
        "price": 15.99,
        "image_url": "https://images.cdn1.buscalibre.com/fit-in/360x360/52/d3/52d3769fb60a4c597eb4c76cca646f1a.jpg",
        "is_featured": True,
        "description": "Primera novela de la saga de la Fundación de Isaac Asimov.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 30,
        "category_id": 1,
        "author_ids": [1],
    },
    {
        "name": "El Señor de los Anillos: La Comunidad del Anillo",
        "price": 19.99,
        "image_url": "https://www.isliada.org/static/images/2018/08/el-senor-de-los-anillos.jpg",
        "is_featured": True,
        "description": "Primer volumen de la saga de Tolkien.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 25,
        "category_id": 2,
        "author_ids": [2],
    },
    {
        "name": "1984",
        "price": 12.99,
        "image_url": "https://miro.medium.com/v2/resize:fit:1200/1*LTr-PoAlBaNBYcVODU_1IQ.jpeg",
        "is_featured": True,
        "description": "Distopía clásica escrita por George Orwell.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 40,
        "category_id": 1,
        "author_ids": [3],
    },
    {
        "name": "It",
        "price": 18.75,
        "image_url": "https://images.cdn1.buscalibre.com/fit-in/360x360/03/0a/030a419b5cbfda84843b6b9fdc5d8273.jpg",
        "is_featured": False,
        "description": "Terrorífica novela de Stephen King.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 20,
        "category_id": 9,
        "author_ids": [4],
    },
    {
        "name": "Orgullo y prejuicio",
        "price": 10.50,
        "image_url": "https://m.media-amazon.com/images/I/812URWFCPOL._SY425_.jpg",
        "is_featured": True,
        "description": "Obra maestra de Jane Austen.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 15,
        "category_id": 7,
        "author_ids": [5],
    },
    {
        "name": "Sapiens: De animales a dioses",
        "price": 17.99,
        "image_url": "https://m.media-amazon.com/images/I/616SZzMK37L._SL1500_.jpg",
        "is_featured": True,
        "description": "Historia de la humanidad por Yuval Noah Harari.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 50,
        "category_id": 3,
        "author_ids": [6],
    },
    {
        "name": "Cien años de soledad",
        "price": 14.99,
        "image_url": "https://images.librotea.com/uploads/media/2014/04/14/cien-anos-de-soledad-t-d.jpeg",
        "is_featured": True,
        "description": "Obra cumbre del realismo mágico de García Márquez.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 35,
        "category_id": 7,
        "author_ids": [7],
    },
    {
        "name": "Ángeles y demonios",
        "price": 13.99,
        "image_url": "https://assets.lectulandia.com/b/Dan%20Brown/Angeles%20y%20demonios%20(197)/big.jpg",
        "is_featured": False,
        "description": "Thriller de misterio por Dan Brown.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 22,
        "category_id": 9,
        "author_ids": [8],
    },
    {
        "name": "Los miserables",
        "price": 16.99,
        "image_url": "https://m.media-amazon.com/images/I/71OsAlMcW-L._SL1500_.jpg",
        "is_featured": True,
        "description": "Clásico histórico de Victor Hugo.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 28,
        "category_id": 4,
        "author_ids": [9],
    },
    {
        "name": "El arte de la guerra",
        "price": 9.99,
        "image_url": "https://http2.mlstatic.com/D_NQ_NP_670824-MLM85838535565_062025-O-libro-original-tarot-el-arte-de-la-guerra-estuche-sun-t.webp",
        "is_featured": False,
        "description": "Tratado militar y filosófico de Sun Tzu.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 50,
        "category_id": 6,
        "author_ids": [10],
    },
    {
        "name": "La guerra de los mundos",
        "price": 12.49,
        "image_url": "https://proassetspdlcom.cdnstatics2.com/usuaris/libros/thumbs/446ee0ce-6ae8-4b87-81ce-b4b307dc1c68/d_295_510/portada_la-guerra-de-los-mundos-integral_hitotsu-yokoshima_202506131108.webp",
        "is_featured": False,
        "description": "Clásico de ciencia ficción de H.G. Wells.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 30,
        "category_id": 1,
        "author_ids": [1],
    },
    {
        "name": "El Hobbit",
        "price": 13.49,
        "image_url": "https://th.bing.com/th/id/R.0468ea1ac317a6f896ecab60f3ab801f?rik=YlesNaHw178DNQ&amp;pid=ImgRaw&amp;r=0",
        "is_featured": True,
        "description": "Precuela de El Señor de los Anillos.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 30,
        "category_id": 2,
        "author_ids": [2],
    },
    {
        "name": "Rebelión en la granja",
        "price": 9.99,
        "image_url": "https://losresumenes.com/wp-content/uploads/2024/01/George-Orwell-Rebelion-en-la-granja.-Resumen-y-analisis.jpg",
        "is_featured": False,
        "description": "Alegoría política de Orwell.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 20,
        "category_id": 1,
        "author_ids": [3],
    },
    {
        "name": "Carrie",
        "price": 10.99,
        "image_url": "https://cdn1.booknode.com/book_cover/5031/full/carrie-5030936.jpg",
        "is_featured": False,
        "description": "Primera novela publicada por Stephen King.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 18,
        "category_id": 9,
        "author_ids": [4],
    },
    {
        "name": "Emma",
        "price": 11.99,
        "image_url": "https://tse1.mm.bing.net/th/id/OIP.QSQaWQlJh2giLYbj2qYgaQHaKn?r=0&amp;rs=1&amp;pid=ImgDetMain&amp;o=7&amp;rm=3",
        "is_featured": False,
        "description": "Novela de costumbres de Jane Austen.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 16,
        "category_id": 7,
        "author_ids": [5],
    },
    {
        "name": "Homo Deus",
        "price": 18.50,
        "image_url": "https://www.marcialpons.es/media/img/portadas/2016/10/11/9788499926711.jpg",
        "is_featured": False,
        "description": "Futuro de la humanidad según Harari.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 40,
        "category_id": 3,
        "author_ids": [6],
    },
    {
        "name": "El coronel no tiene quien le escriba",
        "price": 10.49,
        "image_url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1167484006i/23875.jpg",
        "is_featured": False,
        "description": "Novela corta de Gabriel García Márquez.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 15,
        "category_id": 7,
        "author_ids": [7],
    },
    {
        "name": "Inferno",
        "price": 14.29,
        "image_url": "https://images.cdn1.buscalibre.com/fit-in/360x360/64/ca/64ca5c8ca10c572b20454ad89147debd.jpg",
        "is_featured": True,
        "description": "Otra entrega de la saga de Robert Langdon.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 22,
        "category_id": 9,
        "author_ids": [8],
    },
    {
        "name": "Notre-Dame de París",
        "price": 15.75,
        "image_url": "https://http2.mlstatic.com/D_NQ_NP_950236-MLU70778482528_082023-O.webp",
        "is_featured": False,
        "description": "También conocida como El jorobado de Notre-Dame.",
        "detail_images": [],
        "rating": 5,
        "product_stock": 25,
        "category_id": 4,
        "author_ids": [9],
    },
    {
        "name": "12 reglas para vivir",
        "price": 16.95,
        "image_url": "https://tse4.mm.bing.net/th/id/OIP.VGs8ZvdGGMU3RRVQdf-MTAAAAA?r=0&amp;rs=1&amp;pid=ImgDetMain&amp;o=7&amp;rm=3",
        "is_featured": True,
        "description": "Guía práctica de Jordan B. Peterson.",
        "detail_images": [],
        "rating": 4,
        "product_stock": 35,
        "category_id": 10,
        "author_ids": [11],
        }

]
